#!/usr/bin/env bash

set -euo pipefail

# Preserve original stdout/stderr for human-facing status lines (FD 3/4)
exec 3>&1 4>&2

### ============================================================================
### USER CONFIG (safe to publish)
###
### Goal: Build + archive + sign + (optionally) notarize a macOS Unreal project.
###
### How to use:
###   - Leave the PROMPT overrides commented out to be asked interactively.
###   - Or uncomment and set overrides to make it non-interactive / CI-friendly.
###   - You can also export environment variables instead of editing this file.
###
### IMPORTANT: Replace any __REPLACE_ME__ placeholders before running.
### ============================================================================

# --- Project paths ---
# Path to your Unreal project root (the folder that contains the .uproject).
REPO_ROOT_DEFAULT="__REPLACE_ME__/YourProjectRoot"

# Name of your .uproject file.
UPROJECT_NAME_DEFAULT="__REPLACE_ME__.uproject"

# Path to your Xcode workspace generated by Unreal (if you use the Xcode archive step).
# NOTE: This is created by Unreal's GenerateProjectFiles on macOS.
XCODE_WORKSPACE_DEFAULT="__REPLACE_ME__.xcworkspace"

# Xcode scheme must be Shared (seen by `xcodebuild -list -workspace ...`)
XCODE_SCHEME_DEFAULT="__REPLACE_ME__"


# Optional: Where to place build artifacts/logs. Defaults under the repo root.
BUILD_DIR_DEFAULT="Build"
LOG_DIR_DEFAULT="Logs/script-logs"

# --- Naming ---
# SHORT_NAME: used for archive/export file/folder names (keep it simple; no spaces recommended).
# LONG_NAME: used for the final zip filename and any user-facing labels.
SHORT_NAME_DEFAULT="__REPLACE_ME__"
LONG_NAME_DEFAULT="__REPLACE_ME__"

# NOTE: Spaces are allowed in paths on macOS, but they can complicate shells/CI.
# This script will warn if it detects spaces so you can decide if you want to rename.


# --- Unreal Engine location ---
# Option A: Set UE_ROOT to your engine install folder, e.g.:
#   /Users/Shared/Epic Games/UE_5.4
#   /Users/Shared/Epic Games/UE_5.5
#   /Users/Shared/Epic Games/UE_5.7
#   /Users/Shared/Epic Games/UE_5.x (custom)
UE_ROOT_DEFAULT="__REPLACE_ME__/UE_5.x"

# Option B: If you already have these exact paths, you can set them directly.
# If UE_ROOT is set correctly, these will be derived automatically.
UAT_SCRIPTS_SUBPATH_DEFAULT="Engine/Build/BatchFiles"
UE_EDITOR_SUBPATH_DEFAULT="Engine/Binaries/Mac/UnrealEditor.app/Contents/MacOS/UnrealEditor"


# --- Signing / notarization ---
# Developer Team ID (for Xcode automatic signing). Find in Apple Developer → Membership.
DEVELOPMENT_TEAM_DEFAULT="__REPLACE_ME__"

# Developer ID Application signing identity (for codesign).
# Example format: "Developer ID Application: Your Company Name (TEAMID)"
SIGN_IDENTITY_DEFAULT="__REPLACE_ME__"

# ExportOptions.plist used by `xcodebuild -exportArchive`.
# You can keep one in the repo (recommended) or point at an absolute path.
EXPORT_PLIST_DEFAULT="__REPLACE_ME__/ExportOptions.plist"

# Notarytool keychain profile name.
# You create this once with: `xcrun notarytool store-credentials "NAME" ...`
NOTARY_PROFILE_DEFAULT="__REPLACE_ME__"


# --- Optional Steam support (disabled by default) ---
# This script can optionally stage + sign Steam's libsteam_api.dylib and optionally
# write steam_appid.txt for local (non-Steam-client) testing.
#
# If you are NOT using Steam, leave ENABLE_STEAM=0 and the script will skip all Steam steps.
ENABLE_STEAM_DEFAULT="0"   # 0 = off, 1 = on

# Steam App ID (only used when ENABLE_STEAM=1 AND WRITE_STEAM_APPID=1).
STEAM_APP_ID_DEFAULT="480" # Spacewar (testing). Replace with your real App ID if needed.

# Write steam_appid.txt next to the executable for local launches (not Steam Client launches).
WRITE_STEAM_APPID_DEFAULT="0"  # 0 = don't write, 1 = write

# Path to libsteam_api.dylib you want to bundle/sign.
# If you use UE's bundled Steamworks SDK, this is usually under Engine/Source/ThirdParty.
STEAM_DYLIB_SRC_DEFAULT="__REPLACE_ME__/libsteam_api.dylib"


# -----------------------------------------------------------------------------
# PROMPT OVERRIDES (optional)
# Uncomment to skip prompts.
# -----------------------------------------------------------------------------

# BUILD_TYPE_OVERRIDE="shipping"      # "shipping" or "development"
# NOTARIZE_OVERRIDE="yes"             # "yes" or "no"

# ENABLE_STEAM_OVERRIDE="0"           # "0" or "1"
# WRITE_STEAM_APPID_OVERRIDE="0"      # "0" or "1"
# STEAM_APP_ID_OVERRIDE="480"


### ============================================================================
### INTERNALS
### ============================================================================

die()  { echo "❌ $*" >&3; exit 1; }
warn() { echo "⚠️  $*" >&3; }
info() { echo "== $* ==" >&3; }

is_placeholder() {
  local v="${1:-}"
  [[ -z "$v" || "$v" == *"__REPLACE_ME__"* ]]
}

require_not_placeholder() {
  local name="$1"; local value="$2"; local hint="$3"
  if is_placeholder "$value"; then
    die "$name is not configured. Set it via env var, edit the USER CONFIG block, or provide an override. Hint: $hint"
  fi
}

#
# Allow environment variables to override defaults without editing the script.
REPO_ROOT="${REPO_ROOT:-$REPO_ROOT_DEFAULT}"
UPROJECT_NAME="${UPROJECT_NAME:-$UPROJECT_NAME_DEFAULT}"
XCODE_WORKSPACE="${XCODE_WORKSPACE:-$XCODE_WORKSPACE_DEFAULT}"
XCODE_SCHEME="${XCODE_SCHEME:-$XCODE_SCHEME_DEFAULT}"
BUILD_DIR_REL="${BUILD_DIR_REL:-$BUILD_DIR_DEFAULT}"
LOG_DIR_REL="${LOG_DIR_REL:-$LOG_DIR_DEFAULT}"

SHORT_NAME="${SHORT_NAME:-$SHORT_NAME_DEFAULT}"
LONG_NAME="${LONG_NAME:-$LONG_NAME_DEFAULT}"

UE_ROOT="${UE_ROOT:-$UE_ROOT_DEFAULT}"
UAT_SCRIPTS_SUBPATH="${UAT_SCRIPTS_SUBPATH:-$UAT_SCRIPTS_SUBPATH_DEFAULT}"
UE_EDITOR_SUBPATH="${UE_EDITOR_SUBPATH:-$UE_EDITOR_SUBPATH_DEFAULT}"

DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM:-$DEVELOPMENT_TEAM_DEFAULT}"
SIGN_IDENTITY="${SIGN_IDENTITY:-$SIGN_IDENTITY_DEFAULT}"
EXPORT_PLIST="${EXPORT_PLIST:-$EXPORT_PLIST_DEFAULT}"
NOTARY_PROFILE="${NOTARY_PROFILE:-$NOTARY_PROFILE_DEFAULT}"

ENABLE_STEAM="${ENABLE_STEAM:-$ENABLE_STEAM_DEFAULT}"
STEAM_APP_ID="${STEAM_APP_ID:-$STEAM_APP_ID_DEFAULT}"
WRITE_STEAM_APPID="${WRITE_STEAM_APPID:-$WRITE_STEAM_APPID_DEFAULT}"
STEAM_DYLIB_SRC="${STEAM_DYLIB_SRC:-$STEAM_DYLIB_SRC_DEFAULT}"

# Derive common paths
REPO="$REPO_ROOT"
UPROJECT_PATH="$REPO_ROOT/$UPROJECT_NAME"
WORKSPACE="$REPO_ROOT/$XCODE_WORKSPACE"
SCHEME="$XCODE_SCHEME"

SCRIPTS="$UE_ROOT/$UAT_SCRIPTS_SUBPATH"
UE_EDITOR="$UE_ROOT/$UE_EDITOR_SUBPATH"

# Artifact roots
BUILD_DIR="$REPO_ROOT/$BUILD_DIR_REL"
LOG_DIR="$REPO_ROOT/$LOG_DIR_REL"

#
# Validate required config early (fail fast with helpful messages)
require_not_placeholder "REPO_ROOT" "$REPO_ROOT" "Example: /Users/you/Documents/Unreal Projects/MyGame"
require_not_placeholder "UPROJECT_NAME" "$UPROJECT_NAME" "Example: MyGame.uproject"
require_not_placeholder "UE_ROOT" "$UE_ROOT" "Example: /Users/Shared/Epic Games/UE_5.7"
require_not_placeholder "DEVELOPMENT_TEAM" "$DEVELOPMENT_TEAM" "Example: ABCDE12345"
require_not_placeholder "SIGN_IDENTITY" "$SIGN_IDENTITY" "Example: Developer ID Application: Your Company (ABCDE12345)"
require_not_placeholder "EXPORT_PLIST" "$EXPORT_PLIST" "Point at an ExportOptions.plist compatible with Developer ID exports"
require_not_placeholder "SHORT_NAME" "$SHORT_NAME" "Example: MG"
require_not_placeholder "LONG_NAME" "$LONG_NAME" "Example: MyGame"

# These are only required if you are using the Xcode archive/export steps.
require_not_placeholder "XCODE_WORKSPACE" "$XCODE_WORKSPACE" "Example: YourProject (Mac).xcworkspace"
require_not_placeholder "XCODE_SCHEME" "$XCODE_SCHEME" "Example: YourProject"

warn_if_has_spaces() {
  local name="$1"; local value="$2"
  if [[ "$value" == *" "* ]]; then
    warn "$name contains spaces: '$value'"
    warn "  This is supported, but can complicate CI/shell scripts. Consider renaming to remove spaces if you're early in the project."
  fi
}

warn_if_has_spaces "REPO_ROOT" "$REPO_ROOT"
warn_if_has_spaces "UPROJECT_NAME" "$UPROJECT_NAME"
warn_if_has_spaces "XCODE_WORKSPACE" "$XCODE_WORKSPACE"
warn_if_has_spaces "XCODE_SCHEME" "$XCODE_SCHEME"
warn_if_has_spaces "SHORT_NAME" "$SHORT_NAME"
warn_if_has_spaces "LONG_NAME" "$LONG_NAME"

# Only required if you enable notarization.
if [[ "${NOTARIZE_OVERRIDE:-}" == "yes" || "${NOTARIZE_OVERRIDE:-}" == "no" ]]; then
  : # validated later
else
  # If they don't override, we'll ask; still validate placeholder now so the prompt doesn't hide a misconfig.
  require_not_placeholder "NOTARY_PROFILE" "$NOTARY_PROFILE" "Run: xcrun notarytool store-credentials \"NAME\" ..."
fi

# Optional Steam validation (only when enabled)
if [[ "$ENABLE_STEAM" == "1" ]]; then
  if is_placeholder "$STEAM_DYLIB_SRC"; then
    die "ENABLE_STEAM=1 but STEAM_DYLIB_SRC is not set. Point it at libsteam_api.dylib or set ENABLE_STEAM=0."
  fi
fi

# Ask up-front (unless overridden)
if [[ -n "${BUILD_TYPE_OVERRIDE:-}" ]]; then
  case "${BUILD_TYPE_OVERRIDE,,}" in
    shipping|s)    BUILD_TYPE="s" ;;
    development|d) BUILD_TYPE="d" ;;
    *) die "BUILD_TYPE_OVERRIDE must be 'shipping' or 'development'" ;;
  esac
else
  read -r -p "Build type? (s=shipping, d=development) [s]: " BUILD_TYPE
  BUILD_TYPE=${BUILD_TYPE:-s}
fi

if [[ "$BUILD_TYPE" =~ ^[Dd]$ ]]; then
  UE_CLIENT_CONFIG="Development"
  XCODE_CONFIG="Development"
  info "Build type: DEVELOPMENT"
else
  UE_CLIENT_CONFIG="Shipping"
  XCODE_CONFIG="Shipping"
  info "Build type: SHIPPING"
fi

if [[ -n "${NOTARIZE_OVERRIDE:-}" ]]; then
  case "${NOTARIZE_OVERRIDE,,}" in
    yes|y) DO_NOTARIZE=0 ;;
    no|n)  DO_NOTARIZE=1 ;;
    *) die "NOTARIZE_OVERRIDE must be 'yes' or 'no'" ;;
  esac
else
  read -r -p "Notarize + staple this build? (Y/n) " NOTARIZE_ANSWER
  if [[ "${NOTARIZE_ANSWER:-Y}" =~ ^[Nn]$ ]]; then
    DO_NOTARIZE=1
  else
    DO_NOTARIZE=0
  fi
fi

# Optional Steam overrides
if [[ -n "${ENABLE_STEAM_OVERRIDE:-}" ]]; then
  ENABLE_STEAM="$ENABLE_STEAM_OVERRIDE"
fi
if [[ -n "${WRITE_STEAM_APPID_OVERRIDE:-}" ]]; then
  WRITE_STEAM_APPID="$WRITE_STEAM_APPID_OVERRIDE"
fi
if [[ -n "${STEAM_APP_ID_OVERRIDE:-}" ]]; then
  STEAM_APP_ID="$STEAM_APP_ID_OVERRIDE"
fi

# Logging (keep logs OUTSIDE Build/, since Build/ is often wiped each run)
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/build_$(date +%Y-%m-%d_%H-%M-%S).log"
exec >>"$LOG_FILE" 2>&1
echo "Log file: $LOG_FILE" >&3

trap 'echo "❌ Script failed at line $LINENO" >&3; exit 1' ERR

# Build outputs
ARCHIVE_PATH="$BUILD_DIR/${SHORT_NAME}.xcarchive"
EXPORT_DIR="$BUILD_DIR/${SHORT_NAME}-export"
ZIP_PATH="$BUILD_DIR/${LONG_NAME}.zip"

# NOTE: ZIP_PATH name is cosmetic (uses LONG_NAME). Change LONG_NAME to match your game.
### ===================================

echo "== Prep output locations ==" >&3
rm -rf "$ARCHIVE_PATH" "$EXPORT_DIR" "$ZIP_PATH" "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

info "Sanity checks"

# Basic file existence checks
[[ -d "$REPO_ROOT" ]] || die "REPO_ROOT does not exist: $REPO_ROOT"
[[ -f "$UPROJECT_PATH" ]] || die "UPROJECT not found: $UPROJECT_PATH"
[[ -d "$SCRIPTS" ]] || die "UAT scripts folder not found: $SCRIPTS"
[[ -x "$SCRIPTS/RunUAT.sh" ]] || die "RunUAT.sh not executable or missing: $SCRIPTS/RunUAT.sh"
[[ -x "$UE_EDITOR" ]] || die "UnrealEditor not found/executable: $UE_EDITOR"

# Xcode workspaces are directory bundles (".xcworkspace" folders), not regular files.
[[ -d "$WORKSPACE" ]] || die "Xcode workspace not found (expected a .xcworkspace directory): $WORKSPACE"
command -v xcodebuild >/dev/null 2>&1 || die "xcodebuild not found. Install Xcode and the Command Line Tools."
command -v codesign  >/dev/null 2>&1 || die "codesign not found (unexpected on macOS)."

# Notarization requires Apple tools and a configured notary profile
if [[ "$DO_NOTARIZE" -eq 0 ]]; then
  command -v xcrun >/dev/null 2>&1 || die "xcrun not found. Install Xcode Command Line Tools."
  # We validated NOTARY_PROFILE earlier, but double-check here for clarity.
  require_not_placeholder "NOTARY_PROFILE" "$NOTARY_PROFILE" "Run: xcrun notarytool store-credentials \"NAME\" ..."
fi

# Export options plist must exist if you are exporting
[[ -f "$EXPORT_PLIST" ]] || die "ExportOptions.plist not found: $EXPORT_PLIST"

echo "== Building Game ==" >&3

"$SCRIPTS/RunUAT.sh" BuildCookRun \
  -unrealexe="$UE_EDITOR" \
  -project="$UPROJECT_PATH" \
  -noP4 -build -cook -pak -iostore \
  -targetplatform=Mac -clientconfig="$UE_CLIENT_CONFIG" \
  -stage -package \
  -archive -archivedirectory="$BUILD_DIR" \
  -utf8output -verbose

echo "== Note: UE clientconfig=$UE_CLIENT_CONFIG, Xcode configuration=$XCODE_CONFIG ==" >&3

echo "== Archive (NO CLEAN) with Automatic signing ==" >&3
xcodebuild \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -configuration "$XCODE_CONFIG" \
  -archivePath "$ARCHIVE_PATH" \
  archive \
  CODE_SIGN_STYLE=Automatic \
  DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
  ENABLE_HARDENED_RUNTIME=YES \
  OTHER_CODE_SIGN_FLAGS="--timestamp"

echo "== Export signed app for Developer ID ==" >&3
# Minimal ExportOptions for direct download (Developer ID).
# If you don't already have it, create the file with the XML below.
xcodebuild -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportPath "$EXPORT_DIR" \
  -exportOptionsPlist "$EXPORT_PLIST"

# Locate the exported .app (name can vary; glob safely)
APP_PATH="$(/usr/bin/find "$EXPORT_DIR" -maxdepth 1 -type d -name '*.app' -print -quit)"
if [[ -z "${APP_PATH:-}" ]]; then
  echo "ERROR: No .app found in export dir: $EXPORT_DIR" >&3
  ls -la "$EXPORT_DIR" || true
  exit 2
fi

echo "WRITE_STEAM_APPID: $WRITE_STEAM_APPID" >&3
echo "App: $APP_PATH" >&3

if [[ "$ENABLE_STEAM" == "1" ]]; then
  STEAM_APPID_PATH="$APP_PATH/Contents/MacOS/steam_appid.txt"
  if [[ "${WRITE_STEAM_APPID:-0}" == "1" ]]; then
    echo "== Write steam_appid.txt for local (non-Steam-client) launches (WRITE_STEAM_APPID=1) ==" >&3
    echo "$STEAM_APP_ID" > "$STEAM_APPID_PATH"
    chmod 644 "$STEAM_APPID_PATH"
  else
    # When launching from the Steam client, Steam provides the AppID and a steam_appid.txt can cause confusing test behavior.
    if [[ -f "$STEAM_APPID_PATH" ]]; then
      echo "== Removing steam_appid.txt (Steam client launch should not need it) ==" >&3
      rm -f "$STEAM_APPID_PATH"
    else
      echo "== Not writing steam_appid.txt (Steam client launch should not need it) ==" >&3
    fi
  fi
else
  info "Steam disabled (ENABLE_STEAM=0) — skipping steam_appid.txt"
fi

if [[ "$ENABLE_STEAM" == "1" ]]; then
  info "Ensure Steam dylib is next to the executable (macOS)"

  STEAM_DYLIB_DEST="$APP_PATH/Contents/MacOS/libsteam_api.dylib"

  if [[ ! -f "$STEAM_DYLIB_SRC" ]]; then
    die "Steam dylib source not found: $STEAM_DYLIB_SRC"
  fi

  cp -fv "$STEAM_DYLIB_SRC" "$STEAM_DYLIB_DEST"

  echo "Signing Steam dylib: $STEAM_DYLIB_DEST" >&3
  /usr/bin/codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" "$STEAM_DYLIB_DEST"
else
  info "Steam disabled (ENABLE_STEAM=0) — skipping libsteam_api.dylib staging"
fi

# Entitlements: hardened runtime is required for Developer ID signing.
# Steam overlay / Steam client libraries may require disabling library validation.
# Only enable those entitlements when you actually need them.
ENTITLEMENTS_FILE="$(/usr/bin/mktemp -t ${SHORT_NAME}_entitlements_XXXXXX.plist)"

if [[ "$ENABLE_STEAM" == "1" ]]; then
  cat > "$ENTITLEMENTS_FILE" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.cs.disable-library-validation</key>
  <true/>
  <key>com.apple.security.cs.allow-dyld-environment-variables</key>
  <true/>
</dict>
</plist>
PLIST
else
  # Minimal entitlements file. Keeping it empty is valid for many apps.
  cat > "$ENTITLEMENTS_FILE" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>
PLIST
fi

echo "Using signing identity: $SIGN_IDENTITY" >&3

echo "Re-signing app bundle (deep) to seal added dylib" >&3
/usr/bin/codesign --force --deep --options runtime --timestamp --entitlements "$ENTITLEMENTS_FILE" --sign "$SIGN_IDENTITY" "$APP_PATH"

echo "== Validations (fail fast) ==" >&3

# Resolve the actual executable name from Info.plist
APP_EXE_NAME=$(/usr/bin/defaults read "$APP_PATH/Contents/Info.plist" CFBundleExecutable 2>/dev/null || true)
if [[ -z "${APP_EXE_NAME:-}" ]]; then
  echo "ERROR: Could not read CFBundleExecutable from Info.plist" >&3
  exit 6
fi
EXE_PATH="$APP_PATH/Contents/MacOS/$APP_EXE_NAME"


if [[ ! -f "$EXE_PATH" ]]; then
  echo "ERROR: Expected executable not found: $EXE_PATH" >&3
  exit 7
fi

# Quick sanity: Shipping builds should not have obvious debug/dev markers.
# (This is heuristic; the authoritative check is LogInit: Build: Shipping when running with -log.)
if /usr/bin/strings "$EXE_PATH" | /usr/bin/grep -q "Development"; then
  echo "WARN: Executable contains 'Development' strings. If you see on-screen debug in-game, confirm LogInit shows Shipping." >&3
fi

# 1) If Steam is enabled, verify the main exe references Steam as @loader_path
if [[ "$ENABLE_STEAM" == "1" ]]; then
  /usr/bin/otool -L "$EXE_PATH" | /usr/bin/grep -q "@loader_path/libsteam_api.dylib" || {
    echo "ERROR: Executable does not reference @loader_path/libsteam_api.dylib" >&3
    /usr/bin/otool -L "$EXE_PATH" | /usr/bin/grep steam || true
    exit 8
  }
fi

# 2) Verify signatures strictly (no || true)
/usr/bin/codesign --verify --deep --strict --verbose=2 "$APP_PATH"

# 2b) Show entitlements (log proof)
echo "-- Entitlements (app) --" >&3
ENT_OUT=$(/usr/bin/codesign -d --entitlements :- "$APP_PATH" 2>/dev/null || true)
echo "$ENT_OUT" >&3

if [[ "$ENABLE_STEAM" == "1" ]]; then
  echo "$ENT_OUT" | /usr/bin/grep -n "disable-library-validation" >&3 || { die "disable-library-validation entitlement not present (required for some Steam client/overlay scenarios)"; }
  echo "$ENT_OUT" | /usr/bin/grep -n "allow-dyld-environment-variables" >&3 || { die "allow-dyld-environment-variables entitlement not present (Steam overlay commonly needs this)"; }
fi

# 3) Show team IDs in log for confidence
/usr/bin/codesign -dv --verbose=4 "$APP_PATH" 2>&1 | /usr/bin/grep -E "^(Authority=|TeamIdentifier=)" || true

if [[ "$ENABLE_STEAM" == "1" ]]; then
  /usr/bin/codesign -dv --verbose=4 "$STEAM_DYLIB_DEST" 2>&1 | /usr/bin/grep -E "^(Authority=|TeamIdentifier=)" || true
fi

# Sanity: ensure TeamIdentifier matches for app + dylib
APP_TEAM=$(/usr/bin/codesign -dv --verbose=4 "$APP_PATH" 2>&1 | /usr/bin/awk -F'=' '/^TeamIdentifier=/{print $2; exit}')

if [[ "$ENABLE_STEAM" == "1" ]]; then
  DYLIB_TEAM=$(/usr/bin/codesign -dv --verbose=4 "$STEAM_DYLIB_DEST" 2>&1 | /usr/bin/awk -F'=' '/^TeamIdentifier=/{print $2; exit}')

  echo "TeamIdentifier (app):   ${APP_TEAM:-<none>}" >&3
  echo "TeamIdentifier (dylib): ${DYLIB_TEAM:-<none>}" >&3
  if [[ -n "${APP_TEAM:-}" && -n "${DYLIB_TEAM:-}" && "$APP_TEAM" != "$DYLIB_TEAM" ]]; then
    echo "ERROR: TeamIdentifier mismatch between app and libsteam_api.dylib (dyld will refuse to load it)." >&3
    exit 5
  fi
else
  echo "TeamIdentifier (app):   ${APP_TEAM:-<none>}" >&3
fi

if [[ "$DO_NOTARIZE" -eq 0 ]]; then
  echo "== Zip app for notarization (no extra parent) ==" >&3
  /usr/bin/ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" "$ZIP_PATH"
  echo "Zip: $ZIP_PATH" >&3

  echo "== Notarize ==" >&3
  /usr/bin/xcrun notarytool submit "$ZIP_PATH" --keychain-profile "$NOTARY_PROFILE" --wait

  echo "== Staple ==" >&3
  /usr/bin/xcrun stapler staple "$APP_PATH"

  echo "== Staple validation ==" >&3
  /usr/bin/xcrun stapler validate "$APP_PATH" || true

  echo "== Gatekeeper assessment ==" >&3
  /usr/sbin/spctl -a -vv "$APP_PATH" || true
else
  echo "== Skipping zip/notarization/stapling (per prompt) ==" >&3
fi

echo "REMINDER: Test your distribution path." >&3
echo "  - If distributing via a launcher (Steam, Epic, etc.), test launching from that launcher." >&3
echo "  - If distributing direct-download, test on a separate Mac (or a clean user account) with Gatekeeper enabled." >&3

echo "✅ Done" >&3
echo "App: $APP_PATH" >&3
echo "Zip: $ZIP_PATH" >&3

# Cleanup temp entitlements file
rm -f "$ENTITLEMENTS_FILE" 2>/dev/null || true